use_frameworks!

target 'Skin_Example' do
  #  pod 'Skin', :path => '../'
  pod 'Skin', :podspec => '../Skin.podspec'

  target 'Skin_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
